version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5439:5432
    environment:
      - POSTGRES_DB=heroes
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
