version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16
      - image: circleci/postgres:9.6.2-alpine
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: heroes
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Sequelize migrations and seeds
          command: cd src/db && npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all
      - run:
          name: test
          command: npm test
      - run:
          name: eslint
          command: npm run eslint
